# Generated by Django 5.0 on 2024-01-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artik", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageWeb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("contenu", models.TextField()),
            ],
        ),
    ]
