# Generated by Django 5.0.1 on 2024-01-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artik", "0002_pageweb"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pageweb",
            name="url",
        ),
    ]
