# Generated by Django 5.0.1 on 2024-01-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artik", "0003_remove_pageweb_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pageweb",
            name="contenu",
        ),
        migrations.AddField(
            model_name="pageweb",
            name="url",
            field=models.URLField(default="https://exemple.com", unique=True),
        ),
    ]
