# Generated by Django 5.0.1 on 2024-01-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artik", "0005_alter_pageweb_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageweb",
            name="contenu",
            field=models.TextField(default=""),
        ),
    ]
