# Generated by Django 5.0.1 on 2024-01-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artik", "0006_pageweb_contenu"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageWeb",
        ),
    ]
